config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  root "homes#show"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show], id: /[^\/]+/ do
    member do
      post "follow", to: "following_relationships#create"
      delete "follow", to: "following_relationships#destroy"
    end
  end

  resources :text_shouts, only: [:create]
  resources :image_shouts, only: [:create]

  get :search, to: "search_results#show"
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed_user, class_name: "User"

  validates :follower_id, uniqueness: { scope: :followed_user_id }
end

app/models/image_shout.rb
class ImageShout < ActiveRecord::Base
  has_attached_file :image

  has_one :shout, as: :content, dependent: :destroy

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  belongs_to :content, polymorphic: true

  default_scope { order(created_at: :desc) }

  paginates_per 10

  def self.search(query, content_class = TextShout)
    content_ids = content_class.search(query).select(:id)
    where(
      content_type: content_class.to_s,
      content_id: content_ids
    ).includes(:content, :user)
  end
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
  validates :body, presence: true

  has_one :shout, as: :content, dependent: :destroy

  def self.search(query)
    where("body ILIKE ?", "%#{query}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_many :shouts

  has_many :followed_user_relationships,
    class_name: "FollowingRelationship",
    foreign_key: :follower_id

  has_many :followed_users, through: :followed_user_relationships

  has_many :follower_relationships,
    class_name: "FollowingRelationship",
    foreign_key: :followed_user_id

  has_many :followers, through: :follower_relationships

  def timeline
    Shout.
      where(user_id: self_and_followed_users_ids).
      order(created_at: :desc).
      includes(:content, :user)
  end

  def follow(user)
    followed_users << user
  end

  def unfollow(user)
    followed_users.delete(user)
  end

  def following?(user)
    followed_users.include?(user)
  end

  def to_param
    username
  end

  private

  def self_and_followed_users_ids
    [id] + followed_user_ids
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers

  before_action :require_login
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @text_shout = TextShout.new
    @image_shout = ImageShout.new
    @shouts = current_user.timeline.page(params[:page])
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
  def create
    user = User.find_by(username: params[:id])
    current_user.follow(user)

    redirect_to user
  end

  def destroy
    user = User.find_by(username: params[:id])
    current_user.unfollow(user)

    redirect_to user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :require_login

  def show
    @user = User.new
  end
end

app/controllers/image_shouts_controller.rb
class ImageShoutsController < ApplicationController
  def create
    image_shout = ImageShout.new(image_shout_params)
    if current_user.shouts.create(content: image_shout)
      redirect_to dashboard_path
    else
      @shouts = current_user.shouts
      render "dashboards/show"
    end
  end

  private

  def image_shout_params
    params.
      require(:image_shout).
      permit(:image)
  end
end

app/controllers/search_results_controller.rb
class SearchResultsController < ApplicationController
  def show
    @query = params[:query]
    @shouts = Shout.search(@query).page(params[:page])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController
  def create
    text_shout = TextShout.new(text_shout_params)
    if current_user.shouts.create(content: text_shout)
      redirect_to dashboard_path
    else
      @shouts = current_user.shouts
      render "dashboards/show"
    end
  end

  private

  def text_shout_params
    params.
      require(:text_shout).
      permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by(username: params[:id])
    @shouts = @user.shouts.includes(:content).page(params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<% if object.errors.any? %>
  <div class="errors">
    <p>Please correct the following:</p>
    <ul>
      <% object.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_followed_users.html.erb
<section class="sidebar followed-users">
  <header>
    <h1>Following</h1>
  </header>

  <div class="users">
    <%= render(user.followed_users) || "Not following anybody." %>
  </div>
</section>

app/views/application/_followers.html.erb
<section class="sidebar followers">
  <header>
    <h1>Followers</h1>
  </header>

  <div class="users">
    <%= render(user.followers) || "No followers." %>
  </div>
</section>

app/views/application/_search_form.html.erb
<section class="sidebar search">
  <header>
    <h1>Search</h1>
  </header>

  <%= form_tag(search_path, method: :get, id: "search-form", class: "search-form") do %>
    <div>
      <%= label_tag :query %>
      <%= search_field_tag :query %>
    </div>
    <div>
      <%= submit_tag "Search" %>
    </div>
  <% end %>
</section>

app/views/application/_sign_in_form.html.erb
<h1>Sign In</h1>
<%= form_for :session, url: session_path, html: { id: "session" } do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username, placeholder: "Username" %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= form.submit "Sign in" %>
  </div>
<% end %>

app/views/application/_sign_up_form.html.erb
<h1>Sign Up</h1>
<%= form_for user do |form| %>
  <%= render "errors", object: user %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username, placeholder: "Username" %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email, placeholder: "Email"  %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, placeholder: "Password" %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<aside>
  <%= render "shouts/text_shouts_form", shout: @text_shout %>
  <%= render "shouts/image_shouts_form", image_shout: @image_shout %>

  <%= render "followers", user: current_user %>
  <%= render "followed_users", user: current_user %>
  <%= render "search_form" %>
</aside>

<section class="timeline">
  <header>
    <h1>My Timeline</h1>
  </header>

  <div class="shouts">
    <%= render @shouts %>
  </div>

  <%= paginate @shouts %>
</section>

app/views/homes/show.html.erb
<div id="home">
  <header>
    <h1>Shoutr</h1>
    <p>Tagline</p>
  </header>

  <div class="home-forms">
    <div class="home-form">
      <%= render "sign_in_form" %>
    </div>

    <div class="home-form">
      <%= render "sign_up_form", user: @user %>
    </div>
  </div>
</div>

app/views/image_shouts/_image_shout.html.erb
<%= image_tag image_shout.image %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoutr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="<%= [controller_name, action_name].join("-") %>">

<header class="top-bar">
  <nav class="feature-links">
    <%= link_to "Home", root_path %>
  </nav>
  <nav class="user-links">
    <% if signed_in? %>
      Hi, <%= current_user.username %>
      (<%= link_to "Sign Out", session_path, method: :delete %>)
    <% else %>
      <%= link_to "Sign In", new_session_path %>
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </nav>
</header>

<section id="main-content">
  <%= yield %>
</section>

</body>
</html>

app/views/search_results/show.html.erb
<aside>
  <%= render "search_form" %>
</aside>

<section class="timeline">
  <header>
    <h1>Search Results for '<%= @query %>'</h1>
  </header>

  <div class="shouts">
    <%= render @shouts %>
  </div>

  <%= paginate @shouts %>
</section>

app/views/shouts/_image_shouts_form.html.erb
<section class="sidebar shout-form image-shout-form">
  <header>
    <h1>Shout an Image</h1>
  </header>

  <%= form_for image_shout do |form| %>
    <div>
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
    <div>
      <%= form.submit "Shout!" %>
    </div>
  <% end %>
</section>

app/views/shouts/_shout.html.erb
<div class="shout">
  <div class="shout-content">
    <%= render shout.content %>
  </div>
  <div class="shout-timestamp">
    Shouted by <%= link_to shout.user.username, shout.user %> <%= time_ago_in_words(shout.created_at) %> ago.
  </div>
</div>

app/views/shouts/_shouts_form.html.erb
<%= form_for shout do |form| %>
  <%= render "errors", object: shout %>

  <div>
    <%= form.label :body %>
    <%= form.text_field :body, placeholder: "Say it here!" %>
  </div>
  <div>
    <%= form.submit "Shout!" %>
  </div>
<% end %>

app/views/shouts/_text_shouts_form.html.erb
<section class="sidebar shout-form text-shout-form">
  <header>
    <h1>New Shout</h1>
  </header>

  <%= form_for shout do |form| %>
    <%= render "errors", object: shout %>

    <div>
      <%= form.label :body %>
      <%= form.text_field :body, placeholder: "Say it here!" %>
    </div>
    <div>
      <%= form.submit "Shout!" %>
    </div>
  <% end %>
</section>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %>

app/views/users/_user.html.erb
<div class="user">
  <%= link_to user.username, user %>
</div>

app/views/users/new.html.erb
<section id="sign_up">
  <%= render "sign_up_form", user: @user %>
</section>

app/views/users/show.html.erb
<aside>
  <%= render "followers", user: @user %>
  <%= render "followed_users", user: @user %>
</aside>

<section class="timeline">
  <header>
    <h1><%= @user.username %>'s Shouts</h1>

    <% unless current_user == @user %>
      <div id="follow-button">
        <% if current_user.following?(@user) %>
          <%= button_to "Unfollow", [:follow, @user], method: :delete %>
        <% else %>
          <%= button_to "Follow", [:follow, @user] %>
        <% end %>
      </div>
    <% end %>
  </header>

  <div class="shouts">
    <%= render @shouts %>
  </div>

  <%= paginate @shouts %>
</section>